apiVersion: 1
datasources:
  - name: MyOTA Prometheus
    uid: myota-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: MyOTA Tempo
    uid: myota-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
  - name: MyOTA Alertmanager
    uid: myota-alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: false
    jsonData:
      implementation: prometheus
