apiVersion: 1
policies:
  - orgId: 1
    receiver: myota-alertmanager
    group_by: [alertname, severity, service_name, http_route, http_request_method]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
